name: endoscopy_ai
description: "Desktop client for endoscopic examinations."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  # http: ^0.13.5
  video_player: ^2.9.2
  video_player_win: ^3.1.1
  file_picker: ^8.3.2
  screenshot: ^3.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.5
  fvp: ^0.32.1
  image: ^4.5.4
  image_picker: ^0.8.7+5
  camera: ^0.10.5+2
  camera_windows: ^0.2.6+2
  camera_platform_interface: ^2.10.0
  ffmpeg_kit_flutter: ^5.1.0 
  permission_handler: ^10.4.4
  flutter_rust_bridge: ^2.10.0
  shared_preferences: ^2.2.2
  mockito: ^5.4.6
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
